project:
  type: website

website:
  title: "Rebecca Barter"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog archive"
        file: blog.qmd
      - text: "Workshops and consulting"
        file: consulting.qmd 
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rlbarter
      - icon: twitter
        href: https://twitter.com/rlbarter
      - icon: rss
        href: index.xml
  google-analytics: "UA-90929425-1"
  site-url: https://www.rebeccabarter.com
  description: "Rebecca Barter's blog"
  twitter-card: true
format:
  html:
    theme: simplex
    linkcolor: "#6633c4"
    code-copy: true
    footnotes-hover: true
    css: styles.css




